import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ChakraProviderWrapper } from './_components/providers/ChakraProviderWrapper';
import ApolloProviderWrapper from './_components/providers/ApolloProviderWrapper';
import ScrollToTopProvider from './_components/providers/ScrollToTopProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Bug Overflow',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ApolloProviderWrapper>
                    <ChakraProviderWrapper>
                        <ScrollToTopProvider>{children}</ScrollToTopProvider>
                    </ChakraProviderWrapper>
                </ApolloProviderWrapper>
            </body>
        </html>
    );
}
